### ISSUE TITLE
Paragraph() error

### ISSUE THREAD

**Issue by RedCarl** [SNWCreations/KookBC#16]
## 您期望得到什么
使用 Paragraph

## 实际得到什么
报错，无法正常运行

## 重现错误的步骤

```
73               .addModule(
                        new SectionModule(
                                new Paragraph(
                                        2,
                                            goldInfo
                                        ),
                                null,
                                null

                        )
                )
```
```
[16:31:00] [Event Executor/ERROR]: Unexpected exception while we attempting to execute command from remote.
snw.jkook.command.CommandException: Something unexpected happened.
	at snw.kookbc.impl.command.CommandManagerImpl.exec(CommandManagerImpl.java:427) ~[CommandManagerImpl.class:0.26.11]
	at snw.kookbc.impl.command.CommandManagerImpl.executeCommand0(CommandManagerImpl.java:256) ~[CommandManagerImpl.class:0.26.11]
	at snw.kookbc.impl.network.ListenerImpl.executeCommand(ListenerImpl.java:209) ~[ListenerImpl.class:0.26.11]
	at snw.kookbc.impl.network.ListenerImpl.event0(ListenerImpl.java:148) ~[ListenerImpl.class:0.26.11]
	at snw.kookbc.impl.network.ListenerImpl.event(ListenerImpl.java:102) ~[ListenerImpl.class:0.26.11]
	at snw.kookbc.impl.network.ListenerImpl.lambda$executeEvent$0(ListenerImpl.java:63) ~[ListenerImpl.class:0.26.11]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Section module only accepts plain-text, kmarkdown and paragraph.
	at snw.jkook.util.Validate.isTrue(Validate.java:28) ~[Validate.class:0.26.11]
	at snw.jkook.message.component.card.module.SectionModule.<init>(SectionModule.java:36) ~[SectionModule.class:0.26.11]
	at cn.miars.kookbot.command.InfoCommand.onCommand(InfoCommand.java:73) ~[InfoCommand.class:?]
	at snw.kookbc.impl.command.CommandManagerImpl.lambda$executeCommand0$4(CommandManagerImpl.java:257) ~[CommandManagerImpl.class:0.26.11]
	at snw.kookbc.impl.command.CommandManagerImpl.exec(CommandManagerImpl.java:421) ~[CommandManagerImpl.class:0.26.11]
	... 8 more
```
## 相关信息

  - KookBC 版本: latest
  - JKook API 版本: latest
  - 您使用的 JKook 插件 的相关信息 (如 名称、作者、版本): 卡尔酱
  - Java 版本: 8
  - 操作系统 (及其版本): MacOS latest

**Comment by xiaoACE6716** [comment]
已解决，并不是Paragraph()有问题

**Comment by SNWCreations** [comment]
修改关闭理由: Issue 问题与实际问题不对应。

**Comment by xiaoACE6716** [comment]
.addModule(
                        new SectionModule(
                                null,
                                new ButtonElement(
                                        Theme.PRIMARY,
                                        "open_shop",
                                        ButtonElement.EventType.RETURN_VAL,
                                        new PlainTextElement(
                                                "前往商城"
                                        )


                                ),
                                Accessory.Mode.LEFT
                        )
                )
