### ISSUE TITLE
0.27.3  Cloud命令调度器解析子命令无效

### ISSUE THREAD

**Issue by cnluminous** [SNWCreations/KookBC#55]
## 实际得到什么
1.Cloud命令解析器解析子命令时无效，无任何相应结果，并且出现报错

2.解析时无执行器出现空指针异常，具体错误代码片段为https://github.com/SNWCreations/KookBC/blob/fe598effc216e3f23e2b5c880f0529fd2ca89883/src/main/java/snw/kookbc/impl/command/cloud/CloudWrappedCommandExecutionHandler.java#L96
可行修复办法:
` } else if(commandObject.getExecutor() != null) { `

## 错误日志
<details><summary>log</summary>
<p>

[21:13:08] [Event Executor/INFO]: Luminous夜光(User ID: 1404527149) issued command: /greet name
[21:13:09] [Event Executor/ERROR]: Unexpected exception while we attempting to execute command from remote.
 snw.jkook.command.CommandException: Something unexpected happened.
        at snw.kookbc.impl.command.cloud.CloudCommandManagerImpl.executeCommand(CloudCommandManagerImpl.java:74) ~[kookbc-0.27.3.jar:0.27.3]
        at snw.kookbc.impl.network.ListenerImpl.executeCommand(ListenerImpl.java:222) ~[kookbc-0.27.3.jar:0.27.3]
        at snw.kookbc.impl.network.ListenerImpl.event0(ListenerImpl.java:154) ~[kookbc-0.27.3.jar:0.27.3]
        at snw.kookbc.impl.network.ListenerImpl.event(ListenerImpl.java:108) ~[kookbc-0.27.3.jar:0.27.3]
        at snw.kookbc.impl.network.ListenerImpl.lambda$handle$0(ListenerImpl.java:69) ~[kookbc-0.27.3.jar:0.27.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: snw.jkook.command.CommandException: Something unexpected happened.
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommandNow(CloudBasedCommandManager.java:181) ~[kookbc-0.27.3.jar:0.27.3]
        at snw.kookbc.impl.command.cloud.CloudCommandManagerImpl.executeCommand(CloudCommandManagerImpl.java:68) ~[kookbc-0.27.3.jar:0.27.3]
        ... 7 more
Caused by: java.lang.NullPointerException: Cannot invoke "snw.jkook.command.CommandExecutor.onCommand(snw.jkook.command.CommandSender, Object[], snw.jkook.message.Message)" because the return value of "snw.jkook.command.JKookCommand.getExecutor()" is null
        at snw.kookbc.impl.command.cloud.CloudWrappedCommandExecutionHandler.execute(CloudWrappedCommandExecutionHandler.java:97) ~[kookbc-0.27.3.jar:0.27.3]
        at cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[kookbc-0.27.3.jar:0.27.3]
        at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[kookbc-0.27.3.jar:0.27.3]
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommand(CloudBasedCommandManager.java:342) ~[kookbc-0.27.3.jar:0.27.3]
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommand(CloudBasedCommandManager.java:277) ~[kookbc-0.27.3.jar:0.27.3]
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommandNow(CloudBasedCommandManager.java:176) ~[kookbc-0.27.3.jar:0.27.3]
        at snw.kookbc.impl.command.cloud.CloudCommandManagerImpl.executeCommand(CloudCommandManagerImpl.java:68) ~[kookbc-0.27.3.jar:0.27.3]
        ... 7 more

</p>
</details> 

## 相关信息

  - KookBC 版本:0.27.3
  - JKook API 版本:0.49.2
  - Java 版本:OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.5.0.5+8-GA (build 17.0.5+8)

**Comment by SNWCreations** [comment]
第二条已在 dev 分支中修复。
第一条等待 @huanmeng-qwq 处理。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月10日(周四) 晚上11:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [SNWCreations/KookBC] 0.27.3  Cloud命令调度器解析子命令无效 (Issue #55)




 
实际得到什么
 
1.Cloud命令解析器解析子命令时无效，无任何相应结果，并且出现报错
 
2.解析时无执行器出现空指针异常，具体错误代码片段为https://github.com/SNWCreations/KookBC/blob/fe598effc216e3f23e2b5c880f0529fd2ca89883/src/main/java/snw/kookbc/impl/command/cloud/CloudWrappedCommandExecutionHandler.java#L96
 可行修复办法:
 } else if(commandObject.getExecutor() != null) {
 https://github.com/cnluminous/KookBC/blob/cd73ec6e9981a1320ac3754afb7f371f9a70a247/src/main/java/snw/kookbc/impl/command/cloud/CloudWrappedCommandExecutionHandler.java#L95C14-L95C14
 
错误日志
 log 
 

[21:13:08] [Event Executor/INFO]: Luminous夜光(User ID: 1404527149) issued command: /greet name
 [21:13:09] [Event Executor/ERROR]: Unexpected exception while we attempting to execute command from remote.
 snw.jkook.command.CommandException: Something unexpected happened.
 at snw.kookbc.impl.command.cloud.CloudCommandManagerImpl.executeCommand(CloudCommandManagerImpl.java:74) ~[kookbc-0.27.3.jar:0.27.3]
 at snw.kookbc.impl.network.ListenerImpl.executeCommand(ListenerImpl.java:222) ~[kookbc-0.27.3.jar:0.27.3]
 at snw.kookbc.impl.network.ListenerImpl.event0(ListenerImpl.java:154) ~[kookbc-0.27.3.jar:0.27.3]
 at snw.kookbc.impl.network.ListenerImpl.event(ListenerImpl.java:108) ~[kookbc-0.27.3.jar:0.27.3]
 at snw.kookbc.impl.network.ListenerImpl.lambda$handle$0(ListenerImpl.java:69) ~[kookbc-0.27.3.jar:0.27.3]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
 at java.lang.Thread.run(Thread.java:833) ~[?:?]
 Caused by: snw.jkook.command.CommandException: Something unexpected happened.
 at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommandNow(CloudBasedCommandManager.java:181) ~[kookbc-0.27.3.jar:0.27.3]
 at snw.kookbc.impl.command.cloud.CloudCommandManagerImpl.executeCommand(CloudCommandManagerImpl.java:68) ~[kookbc-0.27.3.jar:0.27.3]
 ... 7 more
 Caused by: java.lang.NullPointerException: Cannot invoke "snw.jkook.command.CommandExecutor.onCommand(snw.jkook.command.CommandSender, Object[], snw.jkook.message.Message)" because the return value of "snw.jkook.command.JKookCommand.getExecutor()" is null
 at snw.kookbc.impl.command.cloud.CloudWrappedCommandExecutionHandler.execute(CloudWrappedCommandExecutionHandler.java:97) ~[kookbc-0.27.3.jar:0.27.3]
 at cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[kookbc-0.27.3.jar:0.27.3]
 at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[kookbc-0.27.3.jar:0.27.3]
 at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommand(CloudBasedCommandManager.java:342) ~[kookbc-0.27.3.jar:0.27.3]
 at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommand(CloudBasedCommandManager.java:277) ~[kookbc-0.27.3.jar:0.27.3]
 at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommandNow(CloudBasedCommandManager.java:176) ~[kookbc-0.27.3.jar:0.27.3]
 at snw.kookbc.impl.command.cloud.CloudCommandManagerImpl.executeCommand(CloudCommandManagerImpl.java:68) ~[kookbc-0.27.3.jar:0.27.3]
 ... 7 more
 

   
相关信息
  
KookBC 版本:0.27.3
 
JKook API 版本:0.49.2
 
Java 版本:OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.5.0.5+8-GA (build 17.0.5+8)

**Comment by huanmeng-qwq** [comment]
提供一下复现代码

**Comment by SNWCreations** [comment]
理论上任何有子命令的JKookCommand对象均可复现



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 晚上9:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SNWCreations/KookBC] 0.27.3  Cloud命令调度器解析子命令无效 (Issue #55)




 
提供一下复现代码

**Comment by cnluminous** [comment]
> 提供一下复现代码

```java
     new JKookCommand("greet")
                // You can add many subcommands by using addSubcommand method.
                .addSubcommand(
                        new JKookCommand("name")
                                .executesUser((sender, arguments, message) -> {
                                    if (message == null) {
                                        return; // Invoked by using CommandManager#executeCommand
                                                // You can halt the command execution if you want
                                    }
                                    if (arguments.length == 0) {
                                        message.reply(new MarkdownComponent("No name?"));
                                        return; // there is no argument available, we should return
                                    }
                                    // In JKook API 0.37 (and before), the result of arguments[0] is a String.
                                    // But in JKook API 0.38+, the result is Object.
                                    // Why? Because API 0.38 added the argument parser system,
                                    // You can specify the argument type by using JKookCommand#addArgument.
                                    message.reply(new MarkdownComponent("Hi! " + arguments[0]));
                                })
                )
                .register(this);
``` 

此段代码即可复现

**Comment by huanmeng-qwq** [comment]
5b9201feca7761feecd20ce5274184ad30e771ba 已修复
