### ISSUE TITLE
在私聊对话中回复机器人发送的消息出现异常

### ISSUE THREAD

**Issue by cnluminous** [SNWCreations/KookBC#76]
## 您期望得到什么
获取到被回复的机器人内容消息

## 实际得到什么
java.lang.IllegalArgumentException

## 重现错误的步骤

  1.回复机器人发送的所有内容

## 报错日志
<details><summary>Details</summary>

```java
2024-04-28 22:17:50.226 |- ERROR [Event Executor] com.cnluminous.kookbc.Application [147] -| Unable to create event from payload.
2024-04-28 22:17:50.226 |- ERROR [Event Executor] com.cnluminous.kookbc.Application [148] -| Event payload: Frame{type=EVENT, sn=1, d={"channel_type":"PERSON","type":9,"target_id":"305357727","author_id":"1404527149","content":"123","extra":{"type":9,"code":"846e30454e905e18ec85eadc88121a93","author":{"id":"1404527149","username":"Luminous夜光","identify_num":"6666","online":true,"os":"Websocket","status":1,"avatar":"https://img.kookapp.cn/avatars/2021-03/ifv8kGKgfs0hs0hs.jpg?x-oss-process=style/icon","vip_avatar":"https://img.kookapp.cn/avatars/2021-03/ifv8kGKgfs0hs0hs.jpg?x-oss-process=style/icon","banner":"","nickname":"Luminous夜光","roles":[],"is_vip":false,"vip_amp":false,"bot":false,"nameplate":[],"decorations_id_map":{"join_voice":10011,"background":10208},"is_sys":false},"visible_only":null,"mention":[],"mention_all":false,"mention_roles":[],"mention_here":false,"nav_channels":[],"kmarkdown":{"raw_content":"123","mention_part":[],"mention_role_part":[],"channel_part":[],"spl":[]},"emoji":[],"quote":{"id":"662e4e6818adcae46f03f72f","rong_id":"fa6180ec-0f0b-4bcd-9fdb-39d4282fd290","type":9,"content":"购买成功!订单号为2024042821260040890727149","create_at":1714310760062,"author":{"id":"305357727","username":"测试机器人","identify_num":"2847","online":true,"os":"Websocket","status":0,"avatar":"https://img.kookapp.cn/assets/bot.png?x-oss-process=style/icon","vip_avatar":"https://img.kookapp.cn/assets/bot.png?x-oss-process=style/icon","banner":"","nickname":"测试机器人","roles":[],"is_vip":false,"vip_amp":false,"bot":true,"nameplate":[],"bot_status":0,"tag_info":{"color":"#0096FF","bg_color":"#0096FF33","text":"机器人"},"is_sys":false,"client_id":"Jcvwg9Tw9deaU_NB","verified":false},"can_jump":true},"last_msg_content":"123","send_msg_device":1},"msg_id":"b9af5cfa-23b4-442e-97a0-48692724b465","msg_timestamp":1714313868901,"nonce":"aHMbqa5qIC4i3Hun6TLRqWaK","from_type":1}}
java.lang.IllegalArgumentException: The bucket name of the provided route is unknown. Report to KookBC authors if you saw this!
	at snw.kookbc.impl.network.Bucket.get(Bucket.java:85)
	at snw.kookbc.impl.network.NetworkClient.getBucket(NetworkClient.java:116)
	at snw.kookbc.impl.network.NetworkClient.call(NetworkClient.java:85)
	at snw.kookbc.impl.network.NetworkClient.getRawContent(NetworkClient.java:65)
	at snw.kookbc.impl.network.NetworkClient.get(NetworkClient.java:51)
	at snw.kookbc.impl.HttpAPIImpl.getPrivateMessage(HttpAPIImpl.java:293)
	at snw.kookbc.impl.entity.builder.MessageBuilder.buildPrivateMessage(MessageBuilder.java:113)
	at snw.kookbc.impl.serializer.event.pm.PrivateMessageReceivedEventDeserializer.deserialize(PrivateMessageReceivedEventDeserializer.java:39)
	at snw.kookbc.impl.serializer.event.pm.PrivateMessageReceivedEventDeserializer.deserialize(PrivateMessageReceivedEventDeserializer.java:31)
	at snw.kookbc.impl.serializer.event.BaseEventDeserializer.deserialize(BaseEventDeserializer.java:37)
	at snw.kookbc.impl.serializer.event.BaseEventDeserializer.deserialize(BaseEventDeserializer.java:27)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:991)
	at com.google.gson.Gson.fromJson(Gson.java:1062)
	at com.google.gson.Gson.fromJson(Gson.java:1034)
	at snw.kookbc.impl.event.EventFactory.createEvent(EventFactory.java:79)
	at snw.kookbc.impl.network.ListenerImpl.event0(ListenerImpl.java:145)
	at snw.kookbc.impl.network.ListenerImpl.event(ListenerImpl.java:109)
	at snw.kookbc.impl.network.ListenerImpl.lambda$handle$0(ListenerImpl.java:70)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
``` 
</details> 

## 相关信息

  - KookBC 版本:0.29.0
  - JKook API 版本:0.51.0
  - 您使用的 JKook 插件 的相关信息 (如 名称、作者、版本):Springboot集成
  - Java 版本:17
  - 操作系统 (及其版本):Windows11

**Comment by huanmeng-qwq** [comment]
5cf4fe759f2b6b98abc7b8e8733709240674c442 新增`getTextChannelMessage(String)`时导致

**Comment by SNWCreations** [comment]
对该方法调用的HTTP API分析得其bucket name，补齐到 bucket map即可，我最近较忙，暂时无法抽身。
