### ISSUE TITLE
PrivateMessage报错

### ISSUE THREAD

**Issue by ClemensMine** [SNWCreations/KookBC#81]
**实现代码**
```Java
@EventHandler
    public void onButtonClickEvent(UserClickButtonEvent event){
         PrivateMessage privateMessage = Main.INSTANCE.getCore().getHttpAPI().getPrivateMessage(event.getUser(),event.getMessageId());
}
```
**报错内容**
```
[14:52:21] [Update Checker/INFO]: You are using the latest version! :)
[14:52:25] [Event Executor/INFO]: 私聊消息ID -> 1daabefc-4719-4593-8dfb-0f30c11da4ba
[14:52:25] [Event Executor/ERROR]: Unexpected exception while posting event.
[14:52:25] [Event Executor/ERROR]: java.lang.IllegalStateException: Not a JSON Object: ""
[14:52:25] [Event Executor/ERROR]: 	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:101)
[14:52:25] [Event Executor/ERROR]: 	at snw.kookbc.impl.HttpAPIImpl.getPrivateMessage(HttpAPIImpl.java:306)
[14:52:25] [Event Executor/ERROR]: 	at org.logcraft.events.BindEvent$2.run(BindEvent.java:76)
[14:52:25] [Event Executor/ERROR]: 	at org.logcraft.events.BindEvent.onStartBindButtonClickEvent(BindEvent.java:80)
[14:52:25] [Event Executor/ERROR]: 	at snw.kookbc.impl.event.EventExecutorFactoryImpl.lambda$create$0(EventExecutorFactoryImpl.java:48)
[14:52:25] [Event Executor/ERROR]: 	at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148)
[14:52:25] [Event Executor/ERROR]: 	at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107)
[14:52:25] [Event Executor/ERROR]: 	at snw.kookbc.impl.event.EventManagerImpl.callEvent(EventManagerImpl.java:53)
[14:52:25] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.ListenerImpl.event0(ListenerImpl.java:156)
[14:52:25] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.ListenerImpl.event(ListenerImpl.java:109)
[14:52:25] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.ListenerImpl.lambda$handle$0(ListenerImpl.java:70)
[14:52:25] [Event Executor/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[14:52:25] [Event Executor/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[14:52:25] [Event Executor/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```
请问这个是BUG吗？

**Comment by SNWCreations** [comment]
应该修复了，试试 https://github.com/SNWCreations/KookBC/actions/runs/9330638146 的测试版本？

**Comment by ClemensMine** [comment]
FIXED
