### ISSUE TITLE
OkHttp3 SSL验证错误

### ISSUE THREAD

**Issue by ClemensMine** [SNWCreations/KookBC#83]
## 重现错误的步骤

  1.运行一段时间获得Event时就会报错

## 报错日志

> [09:36:01] [Event Executor/ERROR]: Unable to create event from payload.
[09:36:01] [Event Executor/ERROR]: Event payload: Frame{type=EVENT, sn=24, d={"channel_type":"GROUP","type":9,"target_id":"3986220983085048","author_id":"3356165191","content":"\n/server set phone true","extra":{"type":9,"code":"","guild_id":"9977363072351934","guild_type":0,"channel_name":"文字频道","author":{"id":"3356165191","username":"Clemens_Mine","identify_num":"6666","online":true,"os":"Websocket","status":1,"avatar":"https://img.kookapp.cn/avatars/2024-04/nUZKMLRWdD06j06j.png?x-oss-process=style/icon","vip_avatar":"https://img.kookapp.cn/avatars/2024-04/nUZKMLRWdD06j06j.png?x-oss-process=style/icon","banner":"https://img.kookapp.cn/assets/2024-03/AfrnSJR5fl0ls090.png","nickname":"Clemens_Mine","roles":[36113756],"is_vip":true,"vip_amp":true,"bot":false,"nameplate":[],"decorations_id_map":{"join_voice":10216,"background":10208},"is_sys":false},"visible_only":null,"mention":[],"mention_all":false,"mention_roles":[],"mention_here":false,"nav_channels":[],"kmarkdown":{"raw_content":"/server set phone true","mention_part":[],"mention_role_part":[],"channel_part":[],"spl":[]},"emoji":[],"preview_content":"","last_msg_content":"Clemens_Mine：/server set phone true","send_msg_device":1},"msg_id":"860ffa09-edb9-47c3-9d85-90d6522c51ec","msg_timestamp":1717378560426,"nonce":"NVgViv5WkGfSMutgNxSMdUff","from_type":1}}
[09:36:01] [Event Executor/ERROR]: java.lang.RuntimeException: Unable to load resource
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.storage.EntityStorage.lambda$funcWithRetry$4(EntityStorage.java:280)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.storage.EntityStorage.getChannel(EntityStorage.java:118)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.entity.builder.MessageBuilder.buildChannelMessage(MessageBuilder.java:127)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.serializer.event.channel.ChannelMessageEventDeserializer.deserialize(ChannelMessageEventDeserializer.java:39)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.serializer.event.channel.ChannelMessageEventDeserializer.deserialize(ChannelMessageEventDeserializer.java:31)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.serializer.event.BaseEventDeserializer.deserialize(BaseEventDeserializer.java:37)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.serializer.event.BaseEventDeserializer.deserialize(BaseEventDeserializer.java:27)
[09:36:01] [Event Executor/ERROR]: 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
[09:36:01] [Event Executor/ERROR]: 	at com.google.gson.Gson.fromJson(Gson.java:1227)
[09:36:01] [Event Executor/ERROR]: 	at com.google.gson.Gson.fromJson(Gson.java:1329)
[09:36:01] [Event Executor/ERROR]: 	at com.google.gson.Gson.fromJson(Gson.java:1271)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.event.EventFactory.createEvent(EventFactory.java:79)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.ListenerImpl.event0(ListenerImpl.java:145)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.ListenerImpl.event(ListenerImpl.java:109)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.ListenerImpl.lambda$handle$0(ListenerImpl.java:70)
[09:36:01] [Event Executor/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[09:36:01] [Event Executor/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[09:36:01] [Event Executor/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[09:36:01] [Event Executor/ERROR]: Caused by: java.lang.RuntimeException: Unexpected IOException when we attempting to call request.
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.NetworkClient.call(NetworkClient.java:101)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.NetworkClient.getRawContent(NetworkClient.java:65)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.NetworkClient.get(NetworkClient.java:51)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.storage.EntityStorage.lambda$new$2(EntityStorage.java:91)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.storage.EntityStorage.lambda$funcWithRetry$4(EntityStorage.java:275)
[09:36:01] [Event Executor/ERROR]: 	... 17 more
[09:36:01] [Event Executor/ERROR]: Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1329)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1204)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1151)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:178)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
[09:36:01] [Event Executor/ERROR]: 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
[09:36:01] [Event Executor/ERROR]: 	at snw.kookbc.impl.network.NetworkClient.call(NetworkClient.java:87)
[09:36:01] [Event Executor/ERROR]: 	... 21 more
[09:36:01] [Event Executor/ERROR]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:321)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1313)
[09:36:01] [Event Executor/ERROR]: 	... 49 more
[09:36:01] [Event Executor/ERROR]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
[09:36:01] [Event Executor/ERROR]: 	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
[09:36:01] [Event Executor/ERROR]: 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
[09:36:01] [Event Executor/ERROR]: 	... 55 more

## 相关信息

  - KookBC 版本:0.30.1
  - JKook API 版本:0.52.1
  - Java 版本:11

**Comment by SNWCreations** [comment]
try https://github.com/SNWCreations/KookBC/actions/runs/9384762394

**Comment by ClemensMine** [comment]
FIXED
